CREATE DATABASE EXERCICIO_MONITORIA3
USE EXERCICIO_MONITORIA3;

 CREATE TABLE PRODUTO (
 ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
 NOME_PRODUTO VARCHAR(30),
 COD_CATEGORIA INT
 )

ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES CATEGORIA(COD_CATEGORIA)

CREATE TABLE CATEGORIA(
COD_CATEGORIA INT PRIMARY KEY,
NOME_CATEGORIA VARCHAR(30)
)

INSERT INTO CATEGORIA(COD_CATEGORIA, NOME_CATEGORIA) VALUES(1, 'MATERIAL ESCOLAR'),
(2, 'PRODUTOS DE HIGIENE'),
(3, 'ESCRITORIO'),
(4, 'ELETRONICO')

INSERT INTO PRODUTO(NOME_PRODUTO) VALUES('COMPUTADOR')

SELECT * FROM CATEGORIA
SELECT * FROM PRODUTO

SELECT * FROM CATEGORIA RIGHT JOIN PRODUTO
ON PRODUTO.COD_CATEGORIA = CATEGORIA.COD_CATEGORIA
WHERE PRODUTO.COD_CATEGORIA IS NULL

SELECT * FROM  PRODUTO LEFT JOIN CATEGORIA
ON PRODUTO.COD_CATEGORIA = CATEGORIA.COD_CATEGORIA